apiVersion: batch/v1
kind: Job
metadata:
  name: load-data-job
  labels:
    app: simple-app
    component: job
spec:
  template:
    spec:
      containers:
        - name: load-data-job
          image: bcmehrman/simple-python-app
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: config-app
          command: ['python', 'load.py']
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: bcmehrman/simple-python-app
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: config-app
          command: ['pg_isready']
          args: ['-h', '$(DATABASE_HOST)']
        - name: check-for-schema
          image: bcmehrman/simple-python-app
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: config-app
          command:
            - 'sh'
            - '-c'
            - >
              echo "checking ${DATABASE_NAME}";
              matching_table_count=$(PGPASSWORD="$DATABASE_PASSWORD" psql -U "$DATABASE_USERNAME" -h "$DATABASE_HOST" "$DATABASE_NAME" -c "\\d" | grep -c records);
              echo "match ${matching_table_count}";
              if [ "$matching_table_count" -eq 0 ]; then
                exit 1
              else
                exit 0
              fi