apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: simple-app
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
      component: redis
  template:
    metadata:
      labels:
        app: simple-app
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:3.2.10
          resources:
            requests:
              memory: 50Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 1
