apiVersion: v1
kind: ConfigMap
metadata:
  name: config-app
data:
  SERVER_PORT: '9101'
  DATABASE_URL: postgresql://postgres:password@postgres:5432/simple_database
  FLASK_APP: simple_web_app.app
  PYTHONPATH: /simple_web_app