apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: simple-app
    component: web
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: simple-app
    component: web
